version: '2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec middleman server
    ports:
      - "4567:4567"   # Middleman server
      - "35729:35729" # Live reload
    volumes:
      - "bundler:/bundle"
      - .:/srv/www

volumes:
  bundler:
